#!/usr/bin/env node
/**
 * MISKA technical SEO audit — reads source files, optional live HEAD checks.
 * Usage: node scripts/seo-audit.mjs [--live]
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const BASE = "https://www.miskahealth.in";
const LIVE = process.argv.includes("--live");

const issues = [];
const passes = [];

function read(rel) {
  return fs.readFileSync(path.join(ROOT, rel), "utf8");
}

function issue(priority, area, msg) {
  issues.push({ priority, area, msg });
}

function pass(area, msg) {
  passes.push({ area, msg });
}

// --- Source checks ---

const layout = read("app/layout.tsx");
if (layout.includes("metadataBase") && layout.includes("miskahealth.in")) {
  pass("meta", "metadataBase set to miskahealth.in");
} else {
  issue("P0", "meta", "metadataBase missing or wrong domain");
}

const sitemap = read("app/sitemap.ts");
if (sitemap.includes("blogPosts") && sitemap.includes("products")) {
  pass("sitemap", "Dynamic sitemap includes products + blog");
} else {
  issue("P0", "sitemap", "Sitemap may miss routes");
}
if (sitemap.includes("/cart")) {
  issue("P1", "sitemap", "Sitemap includes /cart — remove (robots disallows)");
}

const robots = read("app/robots.ts");
if (robots.includes("sitemap.xml")) pass("robots", "Sitemap referenced in robots.txt");
else issue("P0", "robots", "Sitemap URL missing from robots.txt");
if (!robots.includes("/admin")) {
  issue("P1", "robots", "Add /admin to disallow list");
}

const blog = read("data/blog.ts");
const blogCount = (blog.match(/slug:\s*"/g) || []).length;
if (blogCount >= 3) pass("content", `${blogCount} blog posts in data/blog.ts`);
else issue("P2", "content", `Only ${blogCount} blog posts — target 2+/month`);

const blogPage = read("app/blog/[slug]/page.tsx");
if (!blogPage.includes("alternates") && !blogPage.includes("canonical")) {
  issue("P1", "meta", "Blog posts missing canonical URLs in generateMetadata");
}
if (!blogPage.includes("openGraph")) {
  issue("P1", "meta", "Blog posts missing Open Graph metadata");
}

const products = read("data/products.ts");
const productSlugs = [...products.matchAll(/slug:\s*"([^"]+)"/g)].map((m) => m[1]);
productSlugs.forEach((slug) => {
  const idx = products.indexOf(`slug: "${slug}"`);
  const block = products.slice(idx, idx + 2500);
  if (!block.includes("seo:")) issue("P1", "products", `Product ${slug} missing seo block`);
});

if (!layout.includes("application/ld+json") && !read("app/page.tsx").includes("application/ld+json")) {
  issue("P1", "structured-data", "No JSON-LD (Organization/Product/Article) detected");
}

const keywords = JSON.parse(read("seo/keywords.json"));
const planned = keywords.keywords.filter((k) => k.status === "planned-content").length;
if (planned > 0) {
  pass("keywords", `${keywords.keywords.length} tracked keywords, ${planned} need new content`);
}

// --- Live checks (optional) ---

async function liveCheck(url) {
  try {
    const res = await fetch(url, { method: "HEAD", redirect: "follow" });
    return res.status;
  } catch {
    return 0;
  }
}

if (LIVE) {
  for (const path of ["/", "/sitemap.xml", "/robots.txt", "/blog"]) {
    const status = await liveCheck(`${BASE}${path}`);
    if (status === 200) pass("live", `${path} → ${status}`);
    else issue("P0", "live", `${path} → HTTP ${status || "failed"}`);
  }
}

// --- Report ---

const reportDir = path.join(ROOT, "seo/reports");
fs.mkdirSync(reportDir, { recursive: true });
const date = new Date().toISOString().slice(0, 10);
const reportPath = path.join(reportDir, `${date}-audit.md`);

const p0 = issues.filter((i) => i.priority === "P0");
const p1 = issues.filter((i) => i.priority === "P1");
const p2 = issues.filter((i) => i.priority === "P2");

const md = `# MISKA SEO Audit — ${date}

## Summary
- **Passes:** ${passes.length}
- **Issues:** ${issues.length} (P0: ${p0.length}, P1: ${p1.length}, P2: ${p2.length})

## P0 — Fix immediately
${p0.map((i) => `- [ ] **${i.area}:** ${i.msg}`).join("\n") || "_None_"}

## P1 — Fix this week
${p1.map((i) => `- [ ] **${i.area}:** ${i.msg}`).join("\n") || "_None_"}

## P2 — Backlog
${p2.map((i) => `- [ ] **${i.area}:** ${i.msg}`).join("\n") || "_None_"}

## Passes
${passes.map((p) => `- ✅ ${p.area}: ${p.msg}`).join("\n")}

---
_Generated by \`npm run seo:audit${LIVE ? " -- --live" : ""}\`_
`;

fs.writeFileSync(reportPath, md);
console.log(`Audit written: seo/reports/${date}-audit.md`);
console.log(`Issues: ${issues.length} | Passes: ${passes.length}`);
process.exit(p0.length > 0 ? 1 : 0);
